# SPDX-License-Identifier: Apache-2.0
# Swirlds/Hiero modules - group ID migrated from com.swirlds to com.hedera.hashgraph at 0.63+
com.swirlds.base=com.hedera.hashgraph:swirlds-base
com.swirlds.config.api=com.hedera.hashgraph:swirlds-config-api
com.swirlds.config.extensions=com.hedera.hashgraph:swirlds-config-extensions
com.swirlds.config.impl=com.hedera.hashgraph:swirlds-config-impl
org.hiero.metrics=com.hedera.hashgraph:hiero-metrics
org.hiero.metrics.openmetrics.httpserver=com.hedera.hashgraph:openmetrics-httpserver
# Jars that are not yet modules used in the 'tools' project
com.google.api.gax=com.google.api:gax
com.google.auth.oauth2=com.google.auth:google-auth-library-oauth2-http
com.google.cloud.core=com.google.cloud:google-cloud-core
com.google.cloud.storage=com.google.cloud:google-cloud-storage
com.google.cloud.nio=com.google.cloud:google-cloud-nio
com.hedera.cryptography.wraps=com.hedera.cryptography:hedera-cryptography-wraps
com.hedera.common.nativesupport=com.hedera.common:hedera-common-nativesupport
