# SPDX-License-Identifier: Apache-2.0
# ----------------------------------------------
# gRPC Config
# ----------------------------------------------
grpc.serverAddress=localhost
grpc.port=40840
# ----------------------------------------------
# BlockStreamConfig
# ----------------------------------------------
blockStream.simulatorMode=PUBLISHER_CLIENT
# ----------------------------------------------
# Prometheus Config
# ----------------------------------------------
# The prometheus endpoint is used by the
# MetricsService to track different metrics.
# This is disabled by default to avoid port
# conflicts with the server prometheus endpoint.
# We might consider enabling this on a different
# port to track simulator metrics from a
# dashboard.
prometheus.endpointEnabled=false
prometheus.endpointPortNumber=16007
# OpenMetrics HTTP server config
metrics.exporter.openmetrics.http.enabled=false
metrics.exporter.openmetrics.http.hostname=0.0.0.0
metrics.exporter.openmetrics.http.port=16007
# ----------------------------------------------
# BlockAsFileLargeDataSets config
# ----------------------------------------------
#generator.folderRootPath=/Users/user/Downloads/block-0.0.3-perf
#generator.invalidBlockHash=true

# Optional range configuration
#generator.startBlockNumber=0
#generator.endBlockNumber=2000

#blockStream.maxBlockItemsToStream=100_000_000
#blockStream.streamingMode=MILLIS_PER_BLOCK
#blockStream.millisecondsPerBlock=500
#blockStream.blockItemsBatchSize=1_000
#blockStream.delayBetweenBlockItems=3_000_000
# When this property is active it causes an abrupt disconnect or sending EndOfStream message (NONE/ABRUPT/EOS)
#blockStream.midBlockFailType=NONE
# The number of blocks streamed before the failure
#blockStream.midBlockFailOffset=0

# ----------------------------------------------

# Simulator startup data
#simulator.startup.data.enabled=true

# ----------------------------------------------
# Unordered Stream Configuration
# ----------------------------------------------

# Enables the unordered stream mode. (values: true/false)
#unorderedStream.enabled=false

# Defines which of the crafted blocks are considered available for streaming.
# Ranges are expanded, e.g., [2-4], [6-9], 13 -> 2, 3, 4, 6, 7, 8, 9, 13.
# All blocks up to the latest listed will be generated in CRAFT mode to keep the hashes realistic
#unorderedStream.availableBlocks=[2-4], [6-9], 13

# Coefficient that determines how scrambled the stream sequence will be (range: 0 to 10).
# - 0 -> The sequence follows unorderedStream.fixedStreamingSequence exactly.
# - 1-5 -> Minor sequence variations.
# - 6-10 -> Major sequence changes.
#unorderedStream.sequenceScrambleLevel=10

# Defines the exact streaming sequence when sequenceScrambleLevel is 0.
# Ranges are expanded, e.g., [1-3], 99, [5-6], 4, 55 -> 1, 2, 3, 99, 5, 6, 4, 55.
# Only the elements that exist in both
#unorderedStream.fixedStreamingSequence=[1-3], 99, [5-6], 4, 55
